apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    name: nv.devsecopsday.default
    namespace: default
  spec:
    dlp:
      settings: []
      status: true
    egress:
    - action: allow
      applications:
      - DNS
      name: nv.kube-dns.kube-system-egress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: kube-dns.kube-system
        - key: domain
          op: =
          value: kube-system
        name: nv.kube-dns.kube-system
        original_name: ""
    - action: allow
      applications:
      - MySQL
      name: nv.mysql.default-egress-1
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: mysql.default
        - key: domain
          op: =
          value: default
        name: nv.mysql.default
        original_name: ""
    file: []
    ingress:
    - action: allow
      applications:
      - HTTP
      name: nv.devsecopsday.default-ingress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: konnectivity-agent.kube-system
        - key: domain
          op: =
          value: kube-system
        name: nv.konnectivity-agent.kube-system
        original_name: ""
    - action: allow
      applications:
      - SSL
      name: nv.devsecopsday.default-ingress-1
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria: []
        name: external
        original_name: ""
    process:
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    - action: allow
      allow_update: false
      name: python3
      path: /usr/bin/python3.11
    process_profile:
      baseline: basic
    target:
      policymode: Protect
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: devsecopsday.default
        - key: domain
          op: =
          value: default
        name: nv.devsecopsday.default
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: null
